services:
  - type: web
    name: afours-erp
    runtime: python
    rootDir: afours
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: DATABASE_URL
        value: "REPLACE_WITH_NEON_DATABASE_URL"
